@startuml

interface ITeacherDao {
+ teach(): void
}

class ProxyFactory {
+ ProxyFactory()
+ getProxyInstance(): Object
}

class TeacherDao {
+ teach(): void
}

class Client

ITeacherDao <|.. TeacherDao
ProxyFactory <.. Client
TeacherDao <.. Client

@enduml